version: 17
jobs:
- name: Test
  jobExecutor: system76
  steps:
  - !CommandStep
    name: build
    runInContainer: false
    interpreter: !ShellInterpreter
      shell: bash
      commands:
      - make all
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
    projects: ligmex
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
